# Generated by Django 3.0.4 on 2020-03-22 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Villagename',
            fields=[
                ('snno', models.PositiveIntegerField(blank=True, db_column='snNo', null=True)),
                ('villagename', models.CharField(db_column='villageName', max_length=45, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'villagename',
            },
        ),
        migrations.CreateModel(
            name='Complaints',
            fields=[
                ('slno', models.PositiveIntegerField(db_column='slNo')),
                ('complainno', models.CharField(db_column='complainNo', max_length=10, primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('subject', models.CharField(max_length=450)),
                ('actionby', models.CharField(blank=True, db_column='actionBy', max_length=45, null=True)),
                ('status', models.CharField(blank=True, max_length=10, null=True)),
                ('remarks', models.CharField(blank=True, max_length=45, null=True)),
                ('villagename', models.ForeignKey(db_column='villageName', on_delete=django.db.models.deletion.DO_NOTHING, to='complaints.Villagename')),
            ],
            options={
                'db_table': 'complaints',
            },
        ),
    ]
