# Generated by Django 3.0.4 on 2020-03-25 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaints',
            name='status',
            field=models.TextField(blank=True, null=True),
        ),
    ]
